mytr={
    'az_tarikh':'از تاریخ',
    'ta_tarikh':'تا تاریخ',
    'chehreh':'چهره',
    'pelak':'پلاک',
    'person':'افراد',
    'videos':'ویدئوها',
    'search':'جستجو',
    'az_saat':'از ساعت',
    'moshahede':'مشاهده',
    'radif':'ردیف',
    'tarikh':'تاریخ',
    'saat':'ساعت',
    'tasvir':'تصویر',
    'select_soojeh':'انتخاب سوژه',
    'sabt':'ثبت',
    'sabte_karbare_jadid':'ثبت آی پی کاربر جدید',
    'hazfe_karbar_az_list':'حذف آی پی کاربر از لیست',
    'list_karbaran':'لیست آی پی کاربران',
    'back':'بازگشت',
    'key':'کلید رمزنگاری',
    'sender_ip':'آی پی فرستنده',
    'center_ip':'آی پی مرکز فرماندهی',
    'quality_frame':'کیفیت ارسال تصاویر',
    'url_cam1':'آدرس دوربین اول',
    'url_cam2':'آدرس دوربین دوم',
    'url_cam3':'آدرس دوربین سوم',
    'url_cam4':'آدرس دوربین چهارم',
    'count_frame_detect':'دقت تشخیص تصاویر',
    'save_videos':'ذخیره ویدئوها',
    'update':'به روزرسانی',
    'warning':'اخطار',
    'for_delete_select_ip_before':'برای حذف ابتدا باید آی پی را انتخاب کنید',
    'select_soojeh_first':'لطفا نام سوژه را انتخاب نمایید',
    'soojeh_name_label':'نام سوژه',
    'before_any_connection_select_soojeh_name':'قبل از شروع حتما باید از قسمت تنظیمات نام سوژه را ثبت کنید',
    'general_setting':'تنظیمات عمومی',
    'view_camera_setting':'تنظیمات دوربین ها',
    'save_video_in_sender':'ذخیره ویدئوه ها در فرستنده',
    'show_camera1':'مشاهده دوربین 1',
    'show_camera2':'مشاهده دوربین 2',
    'show_camera3':'مشاهده دوربین 3',
    'show_camera4':'مشاهده دوربین 4',
    'label_camera_1':'دوربین شماره 1',
    'label_camera_2':'دوربین شماره 2',
    'label_camera_3':'دوربین شماره 3',
    'label_camera_4':'دوربین شماره 4',
    'plz_check_sender_ip':'لطفا آی پی فرستنده را بررسی نمایید',
    'plz_check_reciver_ip':'لطفا آی پی مرکز فرماندهی را بررسی نمایید',
    'up':'بالا',
    'middle':'متوسط',
    'down':'پایین',
    'high':'زیاد',
    'middle':'متوسط',
    'low':'کم',
    'done':'انجام شد',
    'select_drive':'انتخاب درایو',
    'copy_past_data':'انتقال اطلاعات',
    'select_copy_paste':'نوع جابجایی',
    'copy':'کپی',
    'cut':'انتقال',
    'masir_projeh':'مسیر رسانه',

}